spring:
  application:
    name: product
  config:
    import:
      - optional:file:.env[.properties]
      - optional:classpath:application-image.yml
      - optional:classpath:application-ai.yml
  profiles:
    active: local
  output:
    ansi:
      enabled: always