dependencies {
    implementation project(':common')
    implementation project(':security')

    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    // JWT
    implementation "io.jsonwebtoken:jjwt-api:${jjwtVersion}"

    testImplementation 'org.springframework:spring-messaging'
    testImplementation 'org.wiremock:wiremock-standalone:3.6.0'
}
