dependencies {
    implementation project(':common')
    implementation project(':security')

    // jpa
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // AOP
    implementation 'org.springframework.boot:spring-boot-starter-aop:4.0.0-M2'

    // Spring security
    implementation 'org.springframework.boot:spring-boot-starter-security'
}
